// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1YrocyrhDXVMo6tJh1q9PPyH9aqsPPuo',
    appId: '1:303003992783:web:e49190cdf2b7a02de2adba',
    messagingSenderId: '303003992783',
    projectId: 'saving-home-8dfe9',
    authDomain: 'saving-home-8dfe9.firebaseapp.com',
    storageBucket: 'saving-home-8dfe9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrtzWp0KLYoEjCycCV3aDKE9OLaJmB404',
    appId: '1:303003992783:android:894cfdb513923790e2adba',
    messagingSenderId: '303003992783',
    projectId: 'saving-home-8dfe9',
    storageBucket: 'saving-home-8dfe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3pYg4Azlramf8Jutxu45YO-NERj3Cwos',
    appId: '1:303003992783:ios:2027d0a66f1a9cbce2adba',
    messagingSenderId: '303003992783',
    projectId: 'saving-home-8dfe9',
    storageBucket: 'saving-home-8dfe9.appspot.com',
    iosClientId: '303003992783-2qlvbe066iuspsfr32bipqnrgrppte3q.apps.googleusercontent.com',
    iosBundleId: 'com.savinghome.savinghomeWebview',
  );
}
